name: Auto Tweet News

on:
  schedule:
    - cron: "*/100 * * * *"   # Her 10 dakikada bir (UTC)
  workflow_dispatch:         # Elle tetikleme için

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # tokens.json için cache
      - name: Cache tokens.json
        uses: actions/cache@v4
        with:
          path: tokens.json
          key: tokens-cache

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser openai schedule

      - name: Run poster
        env:
          X_CLIENT_ID: ${{ secrets.X_CLIENT_ID }}
          X_CLIENT_SECRET: ${{ secrets.X_CLIENT_SECRET }}
          X_REFRESH_TOKEN: ${{ secrets.X_REFRESH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python ci_xposter.py --news
